spring.datasource.url=jdbc:postgresql://dpg-d09r7vmuk2gs73coadu0-a.oregon-postgres.render.com/curriculosdb
spring.datasource.username=meubancoo
spring.datasource.password=hWkmSDa7xgCa3uDMOmbBi8pflZMsNjr6

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
